### ISSUE TITLE
Build runner for Team City

### ISSUE THREAD

**Issue by vbliznikov** [IlyaAI/AnFake#2]
It will be nice to have an AnFake TeamCity Runner (see https://confluence.jetbrains.com/display/TCD9/Build+Runner+Plugin) to configure and run AnFake build scripts. For now it could be done using a command line runner but having a special runner have it's own advantages: more precise and clean configuration including parameters, targets, etc.

**Comment by IlyaAI** [comment]
In first turn, AnFake was intended to be a "script alternative of build process template" in TFS. But now, I see it might be useful in cooperation with other CI servers too. TeamCity is the first in such queue.

**Comment by IlyaAI** [comment]
https://github.com/IlyaAI/TeamCity.AnFake
